### ISSUE TITLE
[md-select] Select is behind dialog

### ISSUE THREAD

**Issue by ndabAP** [vuematerial/vue-material#1149]
Version: Beta 1.0.4/1.0.3

![bildschirmfoto vom 2017-11-16 20-01-40](https://user-images.githubusercontent.com/8510570/32910293-2352d218-cb09-11e7-8375-417c9b2e70d5.png)

This seems to fix it:

```
.md-menu-content {
  z-index: 10;
}
```

**Comment by marcosmoura** [comment]
I will fix this ASAP!

**Comment by EthraZa** [comment]
I'm experiencing this on Beta 5.
The bare minimun z-index for me is 110. But I managed to get it working only by adding it using Developers Tool.

Using
```
<style lang="scss" scoped>
  .md-menu-content {
    z-index: 110;
  }
</style>
```
is not working.

**Comment by marcosmoura** [comment]
The style to override Vue Material cannot be scoped, since Vue Material is a 3rd party component and also moves some elements around the dom.

**Comment by mattgrande** [comment]
I'm still seeing this in Beta 8. Should this be fixed?

**Comment by Samuell1** [comment]
@mattgrande next release should fix this.

**Comment by swerky** [comment]
Hi, i'm still experiencing this in 1.0.0-beta-14.
In witch release is this should be fixed?

**Comment by pichtj** [comment]
> Hi, i'm still experiencing this in 1.0.0-beta-14.
> In witch release is this should be fixed?

Same here with 1.0.0-beta-14. Above workaround does not solve the issue. Please reopen.

**Comment by AbingLeopoldo** [comment]
Can you add props that can we iput the number of z-index?
