### ISSUE TITLE
Feature request - Labels for datepickers

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1208]
Since datepickers are effectively form fields, suggesting to have labels to be consistent with the other forms

**Comment by Samuell1** [comment]
This will be problem with overflowing label with date pattern

![obrazok](https://user-images.githubusercontent.com/3110002/33238693-e15b52e0-d292-11e7-911c-dd125f3b77e3.png)

**Comment by marcosmoura** [comment]
This will be supported soon. It is not a hard thing.

**Comment by akomarovsky** [comment]
thanks. waiting for it to be released :)

**Comment by marcosmoura** [comment]
:D

**Comment by goatandsheep** [comment]
@Samuell1 I'm finding I have the exact overflowing issue you were suggesting. Is there a fix to that?

**Comment by Samuell1** [comment]
@goatandsheep That should be fixed in beta-8

**Comment by goatandsheep** [comment]
Awesome! Thanks 😍

**Comment by gwilakers** [comment]
I am still seeing the issue of the overflowing label, even in beta-8. Other styles with the date pickers seem to be a little messed up as well.

**Version**: ^1.0.0-beta-8

![image](https://user-images.githubusercontent.com/2496236/37733133-dec41876-2d25-11e8-8010-59afb875538c.png)

Here is the markup for that area:

```    
<md-card>
      <md-card-header>
        <div class="md-title">Dashboard</div>
        <div class="md-subhead">Search</div>
      </md-card-header>
      <md-card-content>
        <div id="search-date-container">
          <md-datepicker v-model="startDate">
            <label>Start Date</label>
          </md-datepicker>
          <md-datepicker v-model="endDate" placeholder="End Date">
            <label>End Date</label>
          </md-datepicker>
        </div>
        <div id="search-button-container">
          <md-button v-bind:class="{disabled: searchDisabled}" id="search-button" v-on:click="fetchData">Search</md-button>
        </div>
      </md-card-content>
    </md-card>
```

I don't have a ton of styles for that area but here they are:

```
#search-date-container,
#search-button-container {
  float: left;
  display: inline-block;
  padding: 10px 0;
}

#search-date-container {
  width: 80%;

  .md-field {
    width: 48%;
    display: inline-flex;
    float: left;
  }

  .md-datepicker {
    background-color: $infiniscene-dark-gray;

    &:nth-of-type(odd) {
       margin-right: 1% !important;
    }

    &:nth-of-type(even) {
      margin-left: 1% !important;
    }

    i {
      &:after {
        content: none;
      }
    }
  }
}

#search-button-container {
  width: 20%;
  padding-left: 15px;

  #search-button {
    float: right;
  }
}
```
Any help or suggestions would be greatly appreciated. Thanks!
