### ISSUE TITLE
[MdBottomBar] Missing required prop: "to" found in md-bottom-bar-item

### ISSUE THREAD

**Issue by CocoChen917** [vuematerial/vue-material#1237]
```vue
<md-bottom-bar md-sync-route>
  <md-bottom-bar-item to="/hot" md-label="Home" md-icon="home"></md-bottom-bar-item>
  <md-bottom-bar-item to="/mobile" md-label="Posts" md-icon="perm_identity"></md-bottom-bar-item>
  <md-bottom-bar-item to="/formDemo" md-label="Favorites" md-icon="favorite"></md-bottom-bar-item>
</md-bottom-bar>
```
my vue version is 2.5.2, thanks~

**Comment by VdustR** [comment]
Could you reproduce it on [Codepen](https://codepen.io)?

**Comment by Samuell1** [comment]
@CocoChen917 Looks like you using older version where prop `to` doesnt exists.

**Comment by luob5** [comment]
I encounter the same problem  with `"vue-material": "^1.0.0-beta-7"`

project init by vue-cli script: `vue init pwa`,

```vue
// app.vue
<template>
  <div id="app">
    <router-view />
    <md-bottom-bar >
      <md-bottom-bar-item :to="'/home'" md-label="Home" md-icon="home"></md-bottom-bar-item>
      <md-bottom-bar-item :to="'/issue'" md-label="Issue" md-icon="favorite"></md-bottom-bar-item>
    </md-bottom-bar>
  </div>
</template>
```
```js
// router
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/home',
      name: 'home',
      component: Home
    },
    {
      path: '/issue',
      name: 'issue',
      component: Issue
    }
  ]
})
```

I start a minimalist project with this part only, but problem is still there.
it can navigate to correct path when I click the item first time, but at the same time, it throws 
```
 [Vue warn]: Missing required prop: "to"           vue.runtime.esm.js?ff9b:574

found in

---> <MdButton> at src/components/MdButton/MdButton.vue
       <MdBottomBarItem> at src/components/MdBottomBar/MdBottomBarItem.vue
         <MdRipple> at src/components/MdRipple/MdRipple.vue
           <MdBottomBar> at src/components/MdBottomBar/MdBottomBar.vue
             <App> at src/App.vue
               <Root>
```

after that,  items can also active or unactive when click, but the address in browser has no change,and throw this [Vue warning] twice at every click

is this a bug? what can I do

**Comment by Samuell1** [comment]
@luob5 try removing binding put only `to="/issues"`

**Comment by luob5** [comment]
@Samuell1 I've all tried, `to` or `:to`,  not work either

**Comment by luob5** [comment]
now I have to  use `router-link` instead `to`
```vue
<md-bottom-bar class="bottom-bar">
    <router-link class="bottom-bar-item">
        <md-bottom-bar-item>
    </router-link>
    ...
</md-bottom-bar>
```

```css
.bottom-bar {
  display: flex;
}
.bottom-bar-item {
  flex-grow: 1;
}
.md-bottom-bar-item {
  width: 100%;
}
```

**Comment by Samuell1** [comment]
can you check your package-lock? @luob5 because this issue looks like for version 0.8.x

**Comment by luob5** [comment]
@Samuell1 
```json
"vue-material": {
      "version": "1.0.0-beta-7",
      "resolved": "http://registry.npm.taobao.org/vue-material/download/vue-material-1.0.0-beta-7.tgz",
      "integrity": "sha1-zXu8kZ1LQ7cdkfr8m17a1Wvaoyc=",
      "requires": {
        "date-fns": "1.29.0",
        "deepmerge": "2.0.1",
        "fuzzysearch": "1.0.3",
        "is-promise": "2.1.0",
        "popper.js": "1.12.9",
        "raf": "3.4.0",
        "vue": "2.5.13",
        "vue-ga": "1.0.0"
      }
    },
```

it's difficult for me to connect official npm (Great Firewall).
so we have to install dependences by Taobao mirror

`npm install --registry=https://registry.npm.taobao.org`

I'll try again CDN mode tomorrow, thanks

**Comment by luob5** [comment]
official `registry.npmjs.org` not work either, the same problem
```
"vue-material": {
      "version": "1.0.0-beta-7",
      "resolved": "https://registry.npmjs.org/vue-material/-/vue-material-1.0.0-beta-7.tgz",
      "integrity": "sha512-wfhGBLdcmYUcTTFJADdKZld5z8g/8E/AlDo0CVby+RAMY2MaTQ5JKeJ/gJ+N0ZqTsrdooZVNPcYFJoiLanwcoA==",
      "requires": {
        "date-fns": "1.29.0",
        "deepmerge": "2.0.1",
        "fuzzysearch": "1.0.3",
        "is-promise": "2.1.0",
        "popper.js": "1.12.9",
        "raf": "3.4.0",
        "vue": "2.5.13",
        "vue-ga": "1.0.0"
      }
    },
```

**Comment by PNKBizz** [comment]
+1 
Same problem =(

**Comment by CocoChen917** [comment]
@luob5 我去，哥们你最后还是自己写的router-link嵌套么？我中间也用嵌套了，后来觉得麻烦，就滚回去用elementUI了，希望团队修复吧，material一些效果还是比较酷炫的，我用在react里面了，英文的官方文档还是看不习惯～emm.......

**Comment by wozturk** [comment]
same problem here. vue version 2.5.13, vue-material version 1.0.0-beta-7 and vue dev tools showing the to prop is set.
<img width="340" alt="screenshot 2018-02-11 10 19 58" src="https://user-images.githubusercontent.com/12676504/36071839-6ee1f06a-0f15-11e8-9cf5-09acbca94226.png">

`    "vue-material": {
      "version": "1.0.0-beta-7",
      "resolved": "https://registry.npmjs.org/vue-material/-/vue-material-1.0.0-beta-7.tgz",
      "integrity": "sha512-wfhGBLdcmYUcTTFJADdKZld5z8g/8E/AlDo0CVby+RAMY2MaTQ5JKeJ/gJ+N0ZqTsrdooZVNPcYFJoiLanwcoA==",
      "requires": {
        "date-fns": "1.29.0",
        "deepmerge": "2.0.1",
        "fuzzysearch": "1.0.3",
        "is-promise": "2.1.0",
        "popper.js": "1.12.9",
        "raf": "3.4.0",
        "vue": "2.5.13",
        "vue-ga": "1.0.0"
      }
    },`

**Comment by mahapo** [comment]
@Samuell1 +1 Bug is not fixed. Still present on 1.0.0-beta-8.

**Comment by Samuell1** [comment]
@mahapo i cant reproduce it in our dev brach

**Comment by mahapo** [comment]
I tried
`"dependencies": {
    "nuxt": "latest",
    "vue-material": "1.0.0-beta-8"
  },`
and
`  "dependencies": {
    "nuxt": "latest",
    "vue-material": "https://github.com/vuematerial/vue-material#dev"
  },`

**Comment by thecrazything** [comment]
I get the same issue, created vue project using vue-cli `vue init pwa`

```
[Vue warn]: Missing required prop: "to"

found in

---> <MdButton> at src/components/MdButton/MdButton.vue
       <MdBottomBarItem> at src/components/MdBottomBar/MdBottomBarItem.vue
         <MdRipple> at src/components/MdRipple/MdRipple.vue
           <MdBottomBar> at src/components/MdBottomBar/MdBottomBar.vue
             <App> at src\App.vue
               <Root>

```
`vue-material": "^1.0.0-beta-8",
"vue": "^2.5.16",`

```
<md-bottom-bar>
          <md-bottom-bar-item to="/" md-label="Home" md-icon="home"></md-bottom-bar-item>
          <md-bottom-bar-item to="/schedule" md-label="Schedule" md-icon="favorite"></md-bottom-bar-item>
          <md-bottom-bar-item to="/animations" md-label="Animations" md-icon="favorite"></md-bottom-bar-item>
</md-bottom-bar>
```

**Comment by Samuell1** [comment]
@mahapo using version froom dev branch doesnt change anything because we doesnt recompile it everytime

**Comment by otolab** [comment]
This problem seems to have been fixed in 6860d3a004b09baef751724c0d9bf1ebdf92b752

**Comment by Samuell1** [comment]
This should be fixed in new version.

https://github.com/vuematerial/vue-material/releases/tag/v1.0.0-beta-10

**Comment by 8ctopotamus** [comment]
@Samuell1 The `to` prop still doesn't work for me in ^1.0.0-beta-10.2.

To get around this I just did this `<md-bottom-bar-item @click="$router.push('/')" md-label="Home" md-icon="home" />`.
