### ISSUE TITLE
md-table - Select does not work well (vue 2.3.x)

### ISSUE THREAD

**Issue by RadMie** [vuematerial/vue-material#795]
### Steps to reproduce
- click checkbox in table header
- checkboxs is not checked in all rows

### Which browser?
Vue 2.2.6 - works well
Vue 2.3.x - does not work well
Vue Material 0.7.1
Chrome

### Reproduction Link
https://codepen.io/radmie/pen/dWxdjV

**Comment by Bolandish** [comment]
Yeah, i got the same bug :)

**Comment by pablohpsilva** [comment]
Hello! I believe I've fixed the issue. Please, if you guys can, check out this PR #767

**Comment by RadMie** [comment]
I checked on develop branch, the error is still.

**Comment by zorosun** [comment]
I also  checked on develop brand, and the error is still there...

**Comment by pablohpsilva** [comment]
Hello guys! I'll look into it again.

**Comment by pablohpsilva** [comment]
![jun-05-2017 08-26-41](https://cloud.githubusercontent.com/assets/2090635/26782252/059deeea-49c9-11e7-9a6e-14465b3b05c6.gif)

Hello Guys! As you can see, the mdTable selection on development is working OK. And I'm using vue 2.3.3. 

```json
"dependencies": {
  "vue": "^2.3.3"
}
```

But rest assured! I'll look into it deeply, OK? I want to kill every single bug on mdTable before enhancing it.

Thank you once again, guys :)

**Comment by zorosun** [comment]
<a href="https://ibb.co/juGXVv"><img src="https://preview.ibb.co/bSkgOF/Screen_Shot_2560_06_05_at_7_01_05_PM.png" alt="Screen_Shot_2560_06_05_at_7_01_05_PM" border="0"></a><br />

and this is my dependency

```
"dependencies": {
    "vue": "^2.3.3",
    "vue-material": "git://github.com/vuematerial/vue-material.git#develop",
}
```

**Comment by RadMie** [comment]
@zorosun on develop branch in dist directory is version 0.7.1, you must do build

**Comment by zorosun** [comment]
@RadMie Thank you. It worked perfectly! 

@pablohpsilva  Sorry for wasting your time... develop branch working good :)

**Comment by RadMie** [comment]
@pablohpsilva Thank you, now works well.
But, the checkbox is too wide (a few pixels)

**Comment by Ken-Yang** [comment]
I have the same issue too. It only works with 2.2.6.
Here is my dependency.

```
├── vue@2.3.4
├── vue-material@0.7.1
```

**Comment by JoiWilliam** [comment]
@Ken-Yang Maybe you can try to build develop brach, it worked well.
@pablohpsilva I also got this issue when i use npm to install(version 0.7.1), please check it, thanks!

**package dependencies:**
```
"vue": "^2.3.4",
"vue-material": "^0.7.1",
```
